import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  theme: {
    extend: {
      colors: {
        app: {
          bg: "var(--color-bg)",
          bg2: "var(--color-bg2)",
          element: "var(--color-element)",
          "element-alt": "var(--color-element-alt)",
          highlight: "var(--color-element-highlight)",
          accent: "var(--color-accent)",
          font: "var(--color-font)",
        },
      },
      boxShadow: {
        app: "2px 2px 2px var(--color-shadow)",
        popup: "2px 2px 4px var(--color-shadow)",
      },
      fontFamily: {
        app: ["Sarabun", "sans-serif"],
        fontin: ["Fontin", "serif"],
        "fontin-smallcaps": ["Fontin Smallcaps", "Fontin", "serif"],
        "friz-quadrata": ["Friz Quadrata", "Friz Quadrata ITC", "serif"],
      },
    },
  },
  safelist: [
    "active",
    "add",
    "alt",
    "btnPrimary",
    "btnSecondary",
    "current",
    "del",
    "diagError",
    "diagWarning",
    "diagnosticErrorPill",
    "diagnosticRange",
    "diagnosticWarningPill",
    "dictExactMatchFind",
    "dictFound",
    "dictNew",
    "diffInlineAdd",
    "diffInlineDel",
    "diffLine",
    "error",
    "exact",
    "gamePreviewWindow--l",
    "gamePreviewWindow--m",
    "gamePreviewWindow--s",
    "hasChanges",
    "hlPopupActive",
    "hlPopupDictActive",
    "isMissing",
    "lineMismatch",
    "mismatch",
    "missingSource",
    "missingTranslation",
    "mustCreate",
    "needsReview",
    "noPointer",
    "postMigration",
    "selectedA",
    "selectedB",
    "tagRange",
    "vocab",
    "warning",
  ],
};
