import { defineStore } from "pinia";
import { getInitialTestMode } from "~/utils/runtime";

export const EDITOR_STATE_KEYS = [
  "offlineStoreReady",
  "testMode",
  "gameVersion",
  "gameVersionSelected",
  "pendingSingleVersionMigration",
  "migrationInProgress",
  "versionStorageLoading",
  "langs",
  "lang",
  "theme",
  "showSetting",
  "needsInitialSettings",
  "loadingProgress",
  "descs",
  "localDescs",
  "sourceLoaded",
  "filteredDescs",
  "statistic",
  "currentSort",
  "currentSortDir",
  "currentSortIcon",
  "pageSize",
  "paginationPadding",
  "currentPage",
  "searchText",
  "filterSelect",
  "hideDNT",
  "highlightDict",
  "shiftEnterSave",
  "autoOpenNextFile",
  "uiDensity",
  "sideTab",
  "dictionaryFilter",
  "regexFilter",
  "dictionaryFlashId",
  "importDialogVisible",
  "historyItems",
  "historyLoading",
  "historySelectedA",
  "historySelectedB",
  "historyDiffHtml",
  "historyFilepath",
  "historyLang",
  "historyMode",
  "editorVisible",
  "editorCurrentEditingDesc",
  "editorFocusedIndex",
  "editorFocusedColumnIndex",
  "editorOriginalTranslations",
  "editorShowEnglishDiff",
  "editorCompareActive",
  "editorCompareMode",
  "editorCompareTitle",
  "hlPopup",
  "hlPopupReturnInfo",
  "editorBlocks",
  "editorRegexes",
  "dictionary",
  "editorClipboard",
  "gamePreviewFrame",
  "gamePreviewFonts",
  "previewGggVars",
  "gamePreviewSegments",
  "showMultiInstanceGate",
  "instanceTabId",
  "multiInstanceCheckTimer",
  "multiInstanceBypass"
] as const;

export const useEditorStore = defineStore("editor", {
  state: () => ({
      offlineStoreReady: false,
      testMode: getInitialTestMode(),
      gameVersion: "",
      gameVersionSelected: false,
      pendingSingleVersionMigration: null,
      migrationInProgress: false,
      versionStorageLoading: false,
      langs: [
        "French",
        "German",
        "Japanese",
        "Korean",
        "Portuguese",
        "Russian",
        "Simplified Chinese",
        "Spanish",
        "Thai",
        "Traditional Chinese",
      ],
      lang: "",
      theme: 'light',
      showSetting: false,
      needsInitialSettings: true,
      loadingProgress: 0.001,
      descs: [],
      localDescs: {
        descs: [],
        lastModified: 0,
        size: 0,
        status: {}
      },
      sourceLoaded: false,
      filteredDescs: [],
      statistic: {
        hasChanges: 0,
        isMissing: 0,
        needsReview: 0
      },
      currentSort: "english",
      currentSortDir: 'asc',
      currentSortIcon: '▲',
      pageSize: 20,
      paginationPadding: 2,
      currentPage: 1,
      searchText: "",
      filterSelect: "new",
      hideDNT: true,
      highlightDict: true,
      shiftEnterSave: false,
      autoOpenNextFile: true,
      uiDensity: 'compact',

      sideTab: 'dictionary',
      dictionaryFilter: '',
      regexFilter: '',
      dictionaryFlashId: '',

      importDialogVisible: false,

      historyItems: [],
      historyLoading: false,
      historySelectedA: null,
      historySelectedB: null,
      historyDiffHtml: '',
      historyFilepath: '',
      historyLang: '',
      historyMode: 'translation',

      editorVisible: false,
      editorCurrentEditingDesc: null,
      editorFocusedIndex: 0,
      editorFocusedColumnIndex: 0,
      editorOriginalTranslations: [],
      editorShowEnglishDiff: false,
      editorCompareActive: false,
      editorCompareMode: 'translation',
      editorCompareTitle: '',
      hlPopup: {
        visible: false,
        editorIndex: 0,
        openedByBracket: false,
        items: [],
        filtered: [],
        filter: "",
        selectedIndex: 0,
        x: 0,
        y: 0,
        columnIndex: 0,
        width: 0,
        selectedTranslationText: ""
      },
      hlPopupReturnInfo: null,
      editorBlocks: [
        {
          english: "+1 to Maximum [EnergyShield|Energy Shield] per {0} [ItemEvasion|Item Evasion] on Equipped Body Armour",
          englishHLter: "+1 to Maximum <span>[EnergyShield|Energy Shield]</span> per <span>{0}%</span> <span>[ItemEvasion|Item Evasion]</span> on Equipped Body Armour",
          englishDiffHtml: "",
          translation: "",
          isTable: false,
          isMultiline: false,
          tableColumns: [],
          translationDiagnostics: [],
          diagnosticWarningCount: 0,
          diagnosticErrorCount: 0,
          metaLinesEn: 0,
          metaLinesTr: 0,
          metaColsEn: 0,
          metaColsTr: 0,
          metaVarsEn: 0,
          metaVarsTr: 0,
          metaKwEn: 0,
          metaKwTr: 0,
          translationReplace: "",
          words: []
        },
      ],
      editorRegexes: [
        {
          find: "(.+) per (\\d+%) \\b(.+)\\b Quality",
          replace: "$R1 ต่อคุณภาพของ $3 ทุกๆ $2"
        },
        {
          find: "Buff Grants (.+)",
          replace: "บัฟมอบม็อด $R1"
        },
        {
          find: "([^ ]+) (increased|reduced) \\b(.+)\\b Damage",
          replace: "$2ความเสียหาย $3 $1"
        }
      ],
      dictionary: [
        {
          find: "Fire",
          replace: "ไฟ"
        },
      ],
      editorClipboard: "",

      gamePreviewFrame: "m",
      gamePreviewFonts: null,
      previewGggVars: {},
      gamePreviewSegments: [],
      
      // Multi-instance detection
      showMultiInstanceGate: false,
      instanceTabId: Math.random().toString(36).substr(2, 9),
      multiInstanceCheckTimer: null,
      multiInstanceBypass: false,
    }),
});
